# Generated by Django 5.2.16 on 2026-09-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
        ('tracks', '0003_alter_track_audio_file_tracklike'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='tracks.track'),
        ),
    ]
