# Generated by Django 5.2.16 on 2026-08-26 12:03

import tracks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_alter_track_options_track_duration_track_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(upload_to='tracks/', validators=[tracks.validators.validate_audio_file]),
        ),
    ]
