# Generated by Django 5.2.16 on 2026-09-18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0003_alter_track_audio_file"),
        ("tracks", "0003_alter_track_audio_file_tracklike"),
    ]

    operations = []
